"""Initial schema: scenarios, tasks, attempts, generation_jobs.

Mirrors the SQLAlchemy models in app/db/models.py one-to-one. See
DESIGN.md Section 5 (Data Model) for the field-level rationale.

Revision ID: 0001
Revises:
Create Date: 2026-04-18

This migration is hand-authored rather than autogenerated so the
schema lives in code that future contributors can read without
running `alembic upgrade --autogenerate` first.
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: tuple[str, ...] | None = None
depends_on: tuple[str, ...] | None = None


def upgrade() -> None:
    """Create the four core tables and their indices."""
    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(length=32), primary_key=True),
        sa.Column("request_prompt", sa.Text(), nullable=False),
        sa.Column("scene_type", sa.String(length=32), nullable=False),
        sa.Column("scene_setup", sa.Text(), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column("source_image_path", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("search_query", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.create_index("ix_scenarios_created_at", "scenarios", ["created_at"])
    op.create_index("ix_scenarios_scene_type", "scenarios", ["scene_type"])

    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=32), primary_key=True),
        sa.Column(
            "scenario_id",
            sa.String(length=32),
            sa.ForeignKey("scenarios.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("position_index", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("answer_type", sa.String(length=16), nullable=False),
        sa.Column("expected_answer", sa.Text(), nullable=False),
        sa.Column("acceptable_answers", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
    )
    op.create_index("ix_tasks_scenario_id", "tasks", ["scenario_id"])

    op.create_table(
        "attempts",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "task_id",
            sa.String(length=32),
            sa.ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("user_answer", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.create_index("ix_attempts_task_id", "attempts", ["task_id"])
    op.create_index("ix_attempts_attempted_at", "attempts", ["attempted_at"])

    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.String(length=32), primary_key=True),
        sa.Column("request_prompt", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'pending'"),
        ),
        sa.Column("progress_stage", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "scenario_id",
            sa.String(length=32),
            sa.ForeignKey("scenarios.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_generation_jobs_created_at", "generation_jobs", ["created_at"])


def downgrade() -> None:
    """Drop the four tables in reverse-creation order."""
    op.drop_index("ix_generation_jobs_created_at", table_name="generation_jobs")
    op.drop_table("generation_jobs")

    op.drop_index("ix_attempts_attempted_at", table_name="attempts")
    op.drop_index("ix_attempts_task_id", table_name="attempts")
    op.drop_table("attempts")

    op.drop_index("ix_tasks_scenario_id", table_name="tasks")
    op.drop_table("tasks")

    op.drop_index("ix_scenarios_scene_type", table_name="scenarios")
    op.drop_index("ix_scenarios_created_at", table_name="scenarios")
    op.drop_table("scenarios")
